# Generated by Django 4.1.7 on 2023-04-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='important',
        ),
        migrations.RemoveField(
            model_name='company',
            name='not_intersted',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
