# Generated by Django 4.1.7 on 2023-04-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
