# Generated by Django 4.1.7 on 2023-04-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_contact_contact_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_type',
            new_name='typ',
        ),
    ]
